# -*- coding: utf-8 -*-
"""Addition of Two Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGq9ufoimVNbaqVyeiXmnpZUYQlcjQk_
"""



"""Add Two Numbers"""

k=float(input("enter the radius: "))

a=3.14*k**2
print("area of circle: ", a)