# -*- coding: utf-8 -*-
"""Area of Circle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGq9ufoimVNbaqVyeiXmnpZUYQlcjQk_
"""



"""Area of circle"""

r=float(input("enter the radius: "))

a=3.14*r**2
print("area of circle: ", a)