# -*- coding: utf-8 -*-
"""Arithmetic operator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vGq9ufoimVNbaqVyeiXmnpZUYQlcjQk_
"""



"""Arithmetic operation"""

a=int(input("enter the a: "))
b=int(input("enter b: "))
print("sum of a and b is: ", a+b)
print("sum of a and b is: ", a*b)
print("sum of a and b is: ", a/b)
print("sum of a and b is: ", a-b)
print("sum of a and b is: ", a**b)
print("sum of a and b is: ", a%b)